services:
  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11435:11434"
    volumes:
      - ${DEPLOY_WORKSPACE_PATH}/data/ollama_storage:/root/.ollama
    restart: unless-stopped

  youtube-uploader:
    build:
      context: ./uploader-service
      dockerfile: Dockerfile
    container_name: youtube-uploader
    tty: true
    stdin_open: true
    volumes:
      - ${DEPLOY_WORKSPACE_PATH}/uploader-service:/app
      - ${DEPLOY_WORKSPACE_PATH}/data:/app/data
      - ${DEPLOY_WORKSPACE_PATH}/config:/app/config
      - ${DEPLOY_WORKSPACE_PATH}/ollama:/app/ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama-service:11434
    restart: unless-stopped

  jenkins-service:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-service
    user: root
    ports:
      - "9090:8080"
    environment:
      - JENKINS_INITIAL_ADMIN_USER=${JENKINS_INITIAL_ADMIN_USER}
      - JENKINS_INITIAL_ADMIN_PASSWORD=${JENKINS_INITIAL_ADMIN_PASSWORD}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - NOTIFICATION_CREDENTIAL_ID=${NOTIFICATION_CREDENTIAL_ID}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - JENKINS_PROJECT_NAME=${JENKINS_PROJECT_NAME}
      - JENKINS_GITHUB_REPO_URL=${JENKINS_GITHUB_REPO_URL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TZ=${SYSTEM_TIMEZONE}
      - JAVA_OPTS=-Duser.timezone=${SYSTEM_TIMEZONE}
      - PIPELINE_CRON_SCHEDULE=${PIPELINE_CRON_SCHEDULE}
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/var/jenkins_home/jenkins.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 0
    restart: unless-stopped

volumes:
  jenkins_data: